version: "3"
services:
  client:
    build: ./client
    ports:
      - 3460:3460
  inventory:
    build: ./inventory
    ports:
      - 3630:3630
  auth:
    build: ./auth
    ports:
      - 3740:3740