version: "3"
services:
  client:
    build: ./client
    ports:
      - 3001:3001
  inventory:
    build: ./inventory
    ports:
      - 3030:3030
  auth:
    build: ./auth
    ports:
      - 4000:4000